USE CODEGNAN;
CREATE TABLE EMP5(EMP_ID INT,NAME VARCHAR(100),CITY VARCHAR(50));
 INSERT INTO EMP5 VALUES(1,"SAI VARDHAN","LONDAN"),(2,"SAI VISHNU","LONDEN"),(3,"VENKAT","INDIA"),(4,"VENKOT","INDIA");
 SELECT * FROM EMP5;
 
  -- CONCAT
  
 SELECT CONCAT("SAI", " ","VARDHAN") AS FULL_NAME;
 SELECT CONCAT(NAME,"PLACE IS"," ", CITY) AS DETAILS FROM EMP5;
 -- CONCAT_WS
 SELECT CONCAT_WS(" ","SAI","VARDHAN","VENKAT") AS NAMECONCAT;
 SELECT CONCAT_WS(" ",NAME,CITY) AS DETAILS FROM EMP5;
 
 -- LOWER AND UPPER 
 SELECT LOWER("SHIREESH");
 SELECT NAME,UPPER(NAME) AS CAPITAL,CITY,LOWER(CITY) AS SAMLL FROM EMP5;
 -- SUBSTRING
 SELECT SUBSTRING("SAI VARDHAN",3,7) AS STTRRR;
 SELECT NAME, SUBSTRING(NAME,2,5) AS STTRR FROM EMP5;
 
 -- REVERSE
 SELECT REVERSE("SAI");
 SELECT NAME,REVERSE(NAME) AS REV FROM EMP5;
 -- REPLACE
 SELECT REPLACE("SAI VARDHAN","SAI","I") AS REPLACE_NAME;
 SELECT EMP_ID NAME,REPLACE(NAME,"SAI","I") AS REPLACE_NAME FROM EMP5;
 
-- LIKE
SELECT * FROM EMP5 WHERE CITY LIKE "LON__N";
SELECT * FROM EMP5 WHERE NAME LIKE "SAI%";